builds:
- id: kubectl-node-restart
  skip: true
archives:
- id: kubectl-node-restart
  name_template: "{{ .TagName }}.zip"
  wrap_in_directory: false
  format: zip
  files:
  - LICENSE
  - node-restart.sh
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  ids:
  - kubectl-node-restart
  name_template: "{{ .Tag }}"
  extra_files:
    - glob: ./*.zip