build:
  skip: true
archives:
- id: kubectl-node-restart
  name_template: "{{ .TagName }}.zip"
  wrap_in_directory: false
  format: zip
  files:
  - LICENSE
  - node-restart.sh
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'